### PR TITLE
Remove updatedAt field from issue data in push_data_to_ccos

### PR DESCRIPTION
**Pull request by akmadian**
## Fixes

Fixes [creativecommong.github.io-source#523](https://github.com/creativecommons/creativecommons.github.io-source/issues/523) by @dhruvkb 

## Description

This PR only removes the updatedAt field from the issue data. I've checked that there are no other uses of `updatedAt` with git grep and we should be all good.

This is a naive solution just meant to cut the number of commits for now, I'm also looking into other ways of reducing the number of commits and may submit additional PRs if I find any good ones.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
This should be helpful in the interim while we search for better solutions.

**Comment by dhruvkb** [comment]
Assigned to @kgodey to merge.

**Comment by dhruvkb** [comment]
Sorry @akmadian, with creativecommons/creativecommons.github.io-source#543 the cron is no longer needed and can be removed altogether instead. I'll update the issue and you can choose to continue on this PR or open a new one.

**Comment by kgodey** [comment]
I'll merge this, I still haven't taken a look at the other PR.

**Pull request merged**
